---
- name: Ensure the VM volumes do not exist
  script: >
    destroy_virt_volume.sh
    {{ item.name }}
    {{ item.pool }}
  with_items: "{{ volumes }}"
  register: volume_result
  environment: "{{ libvirt_vm_script_env }}"
  changed_when:
    - volume_result is success
    - (volume_result.stdout | from_json).changed | default(True)
  become: yes

- name: Ensure the cloud-init iso does not exist
  file:
    path: "{{ libvirt_volume_default_images_path }}/{{ vm.name }}-cloud-init.iso"
    state: absent
